### ISSUE TITLE
Add playback controls in the video component

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1054]
## Description
Incluir en el componente video los controles de reproducción Play/Pause button como prop.

## Tasks

- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Add to UI Kit

**Comment by AnaMontes11** [comment]
Ahora que estamos metiendo el componente video en Cards y Hero, en pro de la accesibilidad incluimos adicionales los controles Play/Pause por lo que creemos que tiene sentido hacer una definición más detallada sobre cómo atacar este uso de los controles.
Valoramos estas vías:
1-Dejar el componente video actual como primitiva y no tocarlo, y se construya atómico.
2-Que el componente video traiga los controles por defecto.
3-Creando un componente Video Player que incluya el video + controles y a futuro posibilidad de añadir otros controles por ejemplo centrados o fuera del video.

Decidimos que puede tener sentido dejar el componente video como está actualmente y crear un componente Video Player.
