### ISSUE TITLE
noBorderRadius en image, video y skeleton rectangle

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1060]
## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [x] Android ticket
- [x] iOS ticket
- [x] Web ticket

**Comment by yceballost** [comment]
done
