### ISSUE TITLE
Cover Hero component

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1079]
## Description

* Add variant with background image
* Explore bullet style that works in inverse and default environments
* Add variant with image full (Left | Right). Only desktop

## Cover app builder needs
* Allow background none to read the context 
* Include noPaddingY to hero (like headers)
* Slideshow controls spacing (take it in account)
* Allow titleAs property (https://github.com/Telefonica/mistica-design/issues/1716)

## Tasks

- [x] Update specs
- [x] [Design documentation](https://brandfactory.telefonica.com/document/1846#/components/hero/cover-hero)
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-14599)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10067)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1848)
