### ISSUE TITLE
Hero component | Documentation fixes

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1080]
## Description

- [x] Add the tablet version of the hero in the component specs.
- [x] Remove recommended aspect-ratios and link to image and video specs

## Tasks

- [x] Update specs
- [x] [Web ticket](https://jira.tid.es/browse/WEB-792)

**Comment by aweell** [comment]
This was never implemented due to how the grid layout works in tablet, since it's possible to control the height of the hero Image, the hero will behave in tablet the same way it does in mobile.
