### ISSUE TITLE
Aspect Ratio in display cards in Figma

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1091]
## Description
- Add 7:10 to display media card
- Add a boolean prop to display media to on / off aspect ratio
- Remove aspect ratio in display data, media and poster

Web integration is already aligned with this

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
