### ISSUE TITLE
Text-preset Vivo Hub definition

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1095]
## Description
- Preset-5 to Preset-10 from Light to Regular

## Tasks

- [x] Update specs
- [x] Add to Vivo new library
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-12018)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8335)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-822)

**Comment by yceballost** [comment]
branch created @annefranca 
https://www.figma.com/file/aNHyvXe1mqjaelE8XWVQD5/branch/RqfeQRdILCjYGyejbMmFxn/%F0%9F%94%B9-Text-presets-definition?node-id=0%3A1&t=C2f7D29ISPg7HnJC-1

**Comment by BrunoBiagioniNeto** [comment]
@yceballost 
**Preset-1 from 12 to 13 (what about desktop?)**
- Não iremos alterar em Desktop o tamanho da fonte.

Preset-1 até Preset-4 mudaremos o **medium** para **bold** (somente na propriedade) o nome poderá continuar com o **medium**.

**Comment by yceballost** [comment]
> @yceballost **Preset-1 from 12 to 13 (what about desktop?)**
> 
> * Não iremos alterar em Desktop o tamanho da fonte.
> 
> Preset-1 até Preset-4 mudaremos o **medium** para **bold** (somente na propriedade) o nome poderá continuar com o **medium**.

Perfeito!

**Comment by BrunoBiagioniNeto** [comment]
Pessoal, precisamos fazer um ajuste, deixar o preset-1 com 12 no Mobile (Não será atualizado). Como fazemos esse Roll back?

**Comment by yceballost** [comment]
Modificado
