### ISSUE TITLE
Remove O2 classic skin from Mística

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1097]
## Description
O2 classic is not used in products anymore

## Tasks

- [x] Archive tokens file
- [x] Review Design documentation
- [x] Archive o2 classic brand library
- [x] Remove from Themer
- [x] Android pr
- [x] iOS pr
- [x] [Web ticket](https://jira.tid.es/browse/WEB-791)
