### ISSUE TITLE
Snackbar color changes in vivo

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1135]
## Description
Use other colors for snackbar info in Vivo

Only light mode

- Background: `feedbackInfoBackground` →  `vivoPurpleDark`
- TextLink: `textLinkSnackbar ` → `vivoPurpleLight20 `

❗️ Review if we can change textLinkSnackbar for TextSecondaryInverse for all brands and remove `textLinkSnackbar`

## Tasks

- [x] Update tokens
- [x] Add to Vivo library
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-11893)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8268)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-806)

**Comment by yceballost** [comment]
https://www.figma.com/file/ubUZYvoFfbXAWph7TpwtWV/Snackbar%2FCrouton?node-id=302-281&t=j8n7fNEH7nvAiRh9-4
