### ISSUE TITLE
Circle component in Figma

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1137]
## Description
Create this component to have parity with code.

Also create specs

## Tasks

- [x] Create specs
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Android [ticket](https://jira.tid.es/browse/ANDROID-12687)
- [x] iOS [ticket](https://jira.tid.es/browse/IOS-8747)
- [x] Web [ticket](https://jira.tid.es/browse/WEB-832)
