### ISSUE TITLE
Add card-title-preset to poster card component

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1153]
## Description

The poster card should follow the same text style definition as the rest of the cards.

## Tasks

- [x] Update specs
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
