### ISSUE TITLE
Change min-width in buttons

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1154]
## Description
Reduce min-width
Default - 100px
Small - 80px

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] Web ticket

---

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1149

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** March 24, 2023</sup>
### Goal

Ao definir o valor de min-width dos botões.

### Context

Para garantir que tenhamos uma largura mínima, mesmo que seja apenas uma palavra, min-width deve ser usado como uma boa prática. Nossa proposta de largura mínima é 100px. 

### Impact

https://ishadeed.com/article/min-max-css/

### Discussion Questions

Seria possível fazer esse ajuste?

### Do you have a visual proposal?

https://www.figma.com/file/seiNjy7YmPWEY3BfY4WYpp/Novos-componentes---Sprint-1?node-id=22%3A27735&t=gYOdlKhORV0w5rhF-1</div>

**Comment by annefranca** [comment]
@yceballost 

Adicionei na documentação a largura mínima para o Button Default e Small.
[Change min-width in buttons](https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/branch/PGr1qnVJ91Alkj14XJN7iI/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0%3A176&t=ZpJFuouYe0kIBDKM-1)

**Comment by yceballost** [comment]
> @yceballost
> 
> Adicionei na documentação a largura mínima para o Button Default e Small. [Change min-width in buttons](https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/branch/PGr1qnVJ91Alkj14XJN7iI/%F0%9F%94%B8-Buttons-Component-Specs?node-id=0%3A176&t=ZpJFuouYe0kIBDKM-1)

Recuerda poner "en review" la branch de Figma cuando consideres que quieres que revisemos :)
