### ISSUE TITLE
Theme variant alternative + inverse/OverInverse fixes

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1185]
## Description

In order to avoid problems when different components are placed in alternative backgrounds, there's a list of changes to be applied. This issue fixed also when an inverse component is placed on an inverse context (`snapCard` and `highlightedCard`)

* Link to specs: https://www.figma.com/file/pzcfoIj4osTMiOHoChiCFm/%F0%9F%94%B9-%E2%80%8E%E2%80%8ETheme-variant-definition?node-id=0%3A1&t=vIsPOqw7Sz960pHf-1
* PR with color token changes: https://github.com/Telefonica/mistica-design/pull/1128
* **Edit(18/04/23)** PR adding neutralLowAlternative to movistar-classic skin: https://github.com/Telefonica/mistica-design/pull/1191

Add isAlternative context to the ThemeVariant

**Edit(18/04/23)** 
## O2-classic token values

| Color-scheme | Token name | Token value |
| :----------  | :----------  | :----------  |
| light | `backgroundContainerBrand` |  `linear-gradient(to bottom, ${palette.o2Blue}, ${palette.o2GradientSecond} 51%, ${palette.o2GradientThird} 72%, ${palette.o2GradientFourth})`
| light | `backgroundContainerAlternative` |  `palette.grey1`
| light | `neutralLowAlternative` |  `palette.grey2`
| dark | `backgroundContainerBrand` |  `palette.darkModeGrey`
| dark | `backgroundContainerAlternative` |  `palette.darkModeGrey`
| dark | `neutralLowAlternative` | `palette.darkModeGrey6`

## Tasks

- [x] Update specs
- [x] [Design documentation](https://brandfactory.telefonica.com/document/1846#/fundamentals/theming)
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] Update Color libraries
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-11961)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8314)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-818)

**Update 21/04/23**

- [x] Add overInverse variants to row component (Figma Libraries only)

## Development:

* Web PR: https://github.com/Telefonica/mistica-web/pull/722

**Comment by yceballost** [comment]
Reopened to include in figma libraries
