### ISSUE TITLE
Cards [Hover and pressed states]

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1202]
## Description

Add hover state in cards components without buttons
- Media card
- Data card
- Display data card
- Display media card
- Snap card
- Poster card
- Highlighted card

### Highlighted, SnapCard and displayMediaCard

| Element | State | Default ∨ OverInverse | inverse | Inverse/OverInverse |  OverAlternative |
|--------|--------|--------|--------|--------|------- |
| background | `hover` | `backgroundContainerHover` | `backgroundContainerBrandHover` | `backgroundContainerBrandOverInverseHover` | `backgroundContainerAlternativeHover` |
| background | `:active`/`pressed` | `backgroundContainerPressed` | `backgroundContainerBrandPressed` | `backgroundContainerBrandOverInversePressed` | `backgroundContainerAlternativePressed` |

### MediaCard and DataCard

| Element | State | Default ∨ OverInverse | OverAlternative |
|--------|--------|--------| ------ |
| background | `hover` | `backgroundContainerHover`|  `backgroundContainerAlternativeHover`|
| background | `:active`/`pressed` | `backgroundContainerPressed` | `backgroundContainerAlternativePressed`|

### Changes in displayMediaCard and posterCard

Add overlay with the following values

| State | Value (hex) | Value (with applyAlpha) |
| ----- | ---- | ---- |
| `:hover` | `#00000040` | `applyAlpha(#000000, 0.25)` |
| `:active`/`pressed` | `#00000059` | `applyAlpha(#000000, 0.35)` |

**Overlay values doesn't change between dark and light modes**

## Transitions

* All `:hover` and `:active` / `pressed` states have an `ease-in-out` transition timing function.
* `:hover` states have a transition duration of 150ms
* `:active`/`pressed` states have a transition duration of 100ms

## Palette values for all brands

![tokens-states](https://user-images.githubusercontent.com/44420072/235954747-5bd5b0f4-e1f1-449c-b608-b9839050f3bb.png)

## Tasks

- [x] Update specs
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-12685)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8746)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-831)

## Fixes

- [x] https://github.com/Telefonica/mistica-design/issues/1215

**Comment by aweell** [comment]
### Strategies

1. Share :hover and :active states, default and alternative contexts use `backgroundContainerAlternative`, inverse overInverse components use a new token (`backgroundContainerBrandSelected`)
2. Create different states for each of the color scenarios (4).
    * `backgroundContainerHover`
    * `backgroundContainerPressed`
    * `backgroundContainerBrandHover`
    * `backgroundContainerBrandPressed`
    * `backgroundContainerBrandHoverOverInverse`
    * `backgroundContainerBrandPressedOverInverse`
3. Create functions to obtain the previous colors via lightness/saturation changes
   * `backgroundContainerHover` = {light :`backgroundContainer` - 5% lightness, dark: `backgroundContainer` + 5% lightness}
   
### The four color scenarios
   
#### Hover and pressed over default

[See prototype ->](https://www.figma.com/proto/tKdPOfcUALzVIh5oizFbm7/branch/HxuZn5jxtXMb1paPmtBQnD/%F0%9F%94%B8-Cards-Specs?page-id=608%3A1119&node-id=4935-13732&viewport=-4312%2C1512%2C0.84&scaling=min-zoom&starting-point-node-id=4935%3A13732&show-proto-sidebar=1)

| backgroundContainer| backgroundContainerHover | backgroundContainerPressed | 
|--------|--------|--------|
| `white` | `white` - 2% lightness  | `grey1` | 
| `darkModeGrey`| `darkModeGrey` + 5% lightness | `darkModeGrey7` |

#### Hover and pressed in inverse

[See proptotype ->](https://www.figma.com/proto/tKdPOfcUALzVIh5oizFbm7/branch/HxuZn5jxtXMb1paPmtBQnD/%F0%9F%94%B8-Cards-Specs?page-id=608%3A1119&node-id=4935-13842&viewport=-4312%2C1512%2C0.84&scaling=min-zoom&starting-point-node-id=4935%3A13842&show-proto-sidebar=1)

| backgroundContainerBrand| backgroundContainerBrandHover | backgroundBrandContainerPressed | 
|--------|--------|--------|
| brandColor | brandColor - 2% lightness  | brandHighColor | 
| `darkModeGrey`| `darkModeGrey` + 5% lightness | `darkModeGrey7` |

#### Hover and pressed in inverse overInverse

[See prototype ->](https://www.figma.com/proto/tKdPOfcUALzVIh5oizFbm7/branch/HxuZn5jxtXMb1paPmtBQnD/%F0%9F%94%B8-Cards-Specs?page-id=608%3A1119&node-id=4935-13878&viewport=-4312%2C1512%2C0.84&scaling=min-zoom&starting-point-node-id=4935%3A13878&show-proto-sidebar=1)

| brandHigh | backgroundContainerBrandHoverOverInverse | backgroundBrandContainerPressedOverInverse | 
|--------|--------|--------|
| brandHighColor | brandHighColor - 2% lightness  | brandHighColor - 8% lightness | 
| `darkModeGrey`| `darkModeGrey` + 5% lightness | `darkModeGrey7` |

#### Hover and pressed in alternative

| backgroundContainer| backgroundContainerHover | backgroundContainerPressed | 
|--------|--------|--------|
| `white` | `white` - 2% lightness  | `grey1` | 
| `darkModeGrey`| `darkModeGrey` + 5% lightness | `darkModeGrey7` |
 
#### Additional notes

* The color should be transformed to hsl ([lch](https://www.w3.org/TR/css-color-4/#specifying-lab-lch) in the future?), modify the color parameters and be transformed back to hex 
* Automatic changes can be on lightness and saturation color values. Depending of the color-scheme we need to adjust how to obtain the new values (dark: `+`lightness `-`saturation, light: `-`lightness `+`saturation)
* This transformation can be performed by the token generator?
* This strategy could be applied to any component using the container color tokens (e.g. rowList and rowListBoxed)

### Display and poster

Display and poster cards will use a different strategy to show hover and pressed states

[See prototype ->](https://www.figma.com/proto/tKdPOfcUALzVIh5oizFbm7/branch/HxuZn5jxtXMb1paPmtBQnD/%F0%9F%94%B8-Cards-Specs?page-id=1868%3A3853&node-id=4935-13516&viewport=-8285%2C-1700%2C0.99&scaling=min-zoom&starting-point-node-id=4935%3A13516&show-proto-sidebar=1)
