### ISSUE TITLE
Lists [Hover and pressed states]

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1204]
### Tasks

**Update/14/06/23**

**Due to changes in the cards states definition this docs should be updated**

https://www.figma.com/file/Be8QB9onmHunKCCAkIBAVr/branch/LE1mzniQNIUKpmKqqVRIrd/%F0%9F%94%B8-Lists-Specs?type=design&node-id=0%3A1140&t=ZMe2llVee3Nb3UmT-1

## Tasks

- [x] Update specs
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13235)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8940)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1390)

## Related tasks

- [x] https://github.com/Telefonica/mistica-design/issues/1072

**Comment by aweell** [comment]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/638

<div type='discussions-op-text'>

<sup>Originally posted by **aweell** July 29, 2022</sup>
En línea con las conversaciones que se han tenido sobre otros elementos, abro un tema referente a los estados `:hover` y `:active` de las listas para web y una propuesta de cual podría ser el resultado de tener los dos estados en el componente:

Ejemplo de la propuesta:

https://codepen.io/AlexBueno/pen/VwXrByp

Propongo añadir nuevos tokens para los elementos interactivos que tienen el mismo fondo que el background:

| Token name | Light value | Dark value |
| :-----------| :---------- | :---------- |
| `backgroundHover` | `#fafafa` | `#242424`|
| `backgroundPressed` | `#f5f5f5` | `#292929` |</div>
