### ISSUE TITLE
Change border of the unselected chip

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1213]
## Description
Change the color of the unselected chip container border from `border` to `control`.

The reason for this change is that, in darkMode, the chips currently use darkModeGrey for the `border` and `backgroundContainer`. As such, visibility is lost. This change resolves this issue.

<img width="543" alt="Captura de Pantalla 2023-05-05 a las 11 28 19" src="https://user-images.githubusercontent.com/88187691/236424860-e7d055f0-65d2-41f1-a558-41cea46efd05.png">

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [x] Android [ticket](https://jira.tid.es/browse/ANDROID-13224)
- [x] iOS [ticket](https://jira.tid.es/browse/IOS-8935)
- [x] Web ticket

**Comment by yceballost** [comment]
please, include in the description of the issue the reason why of this change

**Comment by AnaMontes11** [comment]
> please, include in the description of the issue the reason why of this change

Done. Thanks
