### ISSUE TITLE
Fix backgroundSkeleton and backgroundSkeletonInverse in darkMode

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1235]
## Description

Figma with the proposal:

https://www.figma.com/file/e9Xftp7VGgOWRg489RVXUq/SkeletonDarkMode?type=design&node-id=0%3A1&t=uXStwZkF9qYfThPD-1

This token should avoid to do the following in the component ImageError:

![Screenshot 2023-05-03 at 09 03 20](https://user-images.githubusercontent.com/44420072/235851101-e385220c-80a7-4074-a1c5-df9e3d960298.png)

## Tasks

- [x] Update brand libraries
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13257)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-8951)
