### ISSUE TITLE
Evolve Feedback Screen

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1252]
## Description
- [x] Include the possibility to add slot area in FeedbackScreen. Already added in Figma
- Change margins 24px → 16px
- Icon size 64px → 48px
- Custom animation for Vivo
	- Pendiente confirmar animaciones de Vivo

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Android [ticket](https://jira.tid.es/browse/ANDROID-13311)
- [x] iOS [ticket](https://jira.tid.es/browse/IOS-8994)
- [x] Web [ticket](https://jira.tid.es/browse/WEB-1402)
