### ISSUE TITLE
Change bordeLow to border in Circle component

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1254]
## Description
Al componente <Circle /> se le puede pasar una prop border para activar el border. Este borde puede llevar un color custom por lo que decidimos actualizar el componente en Figma para que el color por defecto lleve la constante `border` en vez de `borderLow`.

## Tasks

- [x] Update specs
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [x] [Web ticket](https://jira.tid.es/browse/WEB-832)
- Android/iOS no necesitan cambiarlo porque aún no tienen este componente.
