### ISSUE TITLE
Naked Card component

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1259]
## Description
New component variant of Media Card without background and border

Include Naked Snap

## Tasks

- [x] Update specs
- [x] #1424
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13545)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9141)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1454)
