### ISSUE TITLE
Include background color to poster card

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1283]
## Description
Include the possibility to add background color to poster card and switch the content between inverse true/false.

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1498)
