### ISSUE TITLE
Include right text in lists

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1284]
## Description
https://www.figma.com/file/ACXesGuPsCXH36TEL70J9z/Lists-%2F-Advanced?node-id=106%3A1047&t=3hSFTZieqKraB2Vi-1

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13480)
- [x] [iOS](https://jira.tid.es/browse/IOS-9081)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1435)
