### ISSUE TITLE
Aspect ratio in all cards

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1312]
## Description
Add definition to:
- Display data card
- Data card
- Snap card

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13629)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9223)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1497)
