### ISSUE TITLE
Include slot in Media Card Asset

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1321]
## Description
Include in Figma the possibility to change Media Card asset by slot

## Tasks

- [x] Update specs
- [x] #1427
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] Android [ticket](https://jira.tid.es/browse/ANDROID-11582)
- [x] iOS [ticket](https://jira.tid.es/browse/IOS-8015)
- [x] Web [ticket](https://jira.tid.es/browse/WEB-760)
