### ISSUE TITLE
SnapCard description and subtitle color change

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1353]
## Description

In order to have parity between the new `NakedSmallCard` and the current `SnapCard` (`DataSmallCard`), we need to add the description property and change the alignment of the card content.

## Tasks

- [x] [Update specs](https://www.figma.com/file/tKdPOfcUALzVIh5oizFbm7/branch/UJNg9eBsXPsX368b1KMou9/%F0%9F%94%B8-Cards-Specs?type=design&node-id=1373%3A2728&mode=design&t=UcaJ2j8mFv86MQkj-1)
- [ ] Design documentation
- [x] [Add to mobile library](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/IDGJmI6rQBVV48KDu5tsyc/M%C3%ADstica-Mobile?type=design&node-id=0%3A661&mode=design&t=XB8hizwV5hiM9ISQ-1)
- [x] [Add to desktop library](https://www.figma.com/file/DSWhPLyJzbliP1fBrLxDUR/branch/CPApJzqy6oE6OlSA9LKX6f/M%C3%ADstica-Desktop?type=design&node-id=0%3A661&mode=design&t=Vg1WuZHOA1SWFTze-1)
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://github.com/Telefonica/mistica-web/pull/1046)
