### ISSUE TITLE
Image circular fallback

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1365]
## Description
Add fallback state for image and include circular image in Figma.

## Tasks

- [x] Update specs
- [ ] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
