### ISSUE TITLE
Title2 tokens size and weight

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1367]
## Description
Create new tokens that only apply to vivo-new
https://www.figma.com/file/68OcCAsdZZK1qbwbqwrXNl/Titles?type=design&node-id=135-47765&mode=design

## Tasks

- [x] Update specs
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to typekits in figma and reuse it in the header component
- [x] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13616)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9212)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1484)
