### ISSUE TITLE
Add OnAir medium font to Figma

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1404]
## Description
Include medium to o2 font

## Tasks
- [x] Add the new o2 medium weight to figma
- [x] Add the new movistar medium weight to figma
- [x] Change weights in onair library
