### ISSUE TITLE
ButtonLinkDanger component

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1430]
### Description

Create a new buttonLinkDanger

### Tasks

- [x] Update specs
- [x]  Design documentation
- [x]  Add to mobile library
- [x]  Add to desktop library
- [x]  Add to UI Kit
- [x]  Android [ticket](https://jira.tid.es/browse/ANDROID-13950)
- [x]  iOS [ticket](https://jira.tid.es/browse/IOS-9508)
- [x]  Web [ticket](https://jira.tid.es/browse/WEB-1626)

### Related with #903 y #1203

**Comment by AnaMontes11** [comment]
Tiene relación con la #1203

**Comment by yceballost** [comment]
PR in web on going

**Comment by yceballost** [comment]
I included documentation for buttonLinkDanger @AnaMontes11 @aweell 
https://brandfactory.telefonica.com/document/1846#/components/buttons/typology-1
