### ISSUE TITLE
Actions in snackbar/crouton

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1461]
## Tasks

- [x] Update specs
- [x] Mobile component
- [x] Desktop component
- [x] Update BF documentation

## Tickets

- [x] iOS: https://jira.tid.es/browse/IOS-9391
- [x] Android: https://jira.tid.es/browse/ANDROID-13817
- [x] Web: https://jira.tid.es/browse/WEB-1587

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1391

<div type='discussions-op-text'>

<sup>Originally posted by **aweell** August  7, 2023</sup>
### Goal

Allow the possibility to differenciate between an action performed by the button / an action performed in the onClose.

### Context

Currently the actions are mainly focused in the dismiss of the snackbar, but there are cases that could be necesary to perform other actions that are not related to the dismiss, for example: undo actions

https://tinyurl.com/28o3847k

### Impact

.

### Discussion Questions

.

### Additional considerations

.

### Do you have a visual proposal?

https://tinyurl.com/28o3847k</div>
