### ISSUE TITLE
Remove last divider in list

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1478]
## Description
Remove last divider in rowList and accordion component

## Tasks

- [x] Update specs
- [x] Design documentation
- [ ] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13880)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9445)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1601)

**Comment by yceballost** [comment]
OB communicated

**Comment by yceballost** [comment]
Same logic for accordions
