### ISSUE TITLE
→ Accessibility: Components | Inputs

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1487]
#557

In Web, inputs do not respond to text size. This is a very important issue with a11y to fix.

## Tasks

- [x] Update specs
- [ ] Design documentation
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13968)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9520)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1630)

**Comment by yceballost** [comment]
@aweell we need to include tooltip accessibility improvements in cvv field in inputs specs

Commented in mistica-web chat
https://www.w3.org/WAI/ARIA/apg/patterns/tooltip/

**Comment by aweell** [comment]
I reopen this issue to include the feedback provided by vivo:

- [x] Deve haver o aria-live ou role alert no feedback de erro para notificar o usuário (Already in specs)
- [ ] É um critério da WCAG que não devemos usar apenas a cor como diferenciação de feedbacks. Inserir um ícone junto com a mensagem ou bold. Não prevemos assim por enquanto nas specs então poderia entrar como evolução.
