### ISSUE TITLE
→ Accessibility: Components | Lists

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1489]
#557 

Current DOM structure:

```
<div data-testid="list">
  <a  href="https://example.org" target="_blank" rel="noopener noreferrer">
    {...}
  </a>
 </div>

```

Using semantic HTML:

```
<ul data-testid="list">
  <li>
    <a  href="https://example.org" target="_blank" rel="noopener noreferrer">
     {...}
    </a>
  </li>
 </ul>

```

It's possible to use role="list" and role="listitem" instead of semantic html.

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/list_role

The drawback of this approach is not knowing when a list is ordered or unordered.

## Tasks

- [x] [Update specs](https://www.figma.com/file/Be8QB9onmHunKCCAkIBAVr/branch/B9g9a38Qy40U1vSLRlbYdL/%F0%9F%94%B8-Lists-Specs?type=design&node-id=3776%3A6050&mode=design&t=rh2IuEvUcQQQ72aW-1)
- [x] Design documentation
- [X] [Android ticket](https://jira.tid.es/projects/ANDROID/issues/ANDROID-15075?filter=allopenissues)
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1719)

**Comment by yceballost** [comment]
@aweell this issue is cover by this PR? https://github.com/Telefonica/mistica-web/pull/1068

Can we update specs?

**Comment by aweell** [comment]
There's already a branch with the update: https://www.figma.com/file/Be8QB9onmHunKCCAkIBAVr/branch/B9g9a38Qy40U1vSLRlbYdL/%F0%9F%94%B8-Lists-Specs?type=design&node-id=3776%3A6050&mode=design&t=rh2IuEvUcQQQ72aW-1

**Comment by aweell** [comment]
Added pending ANDROID ticket: https://jira.tid.es/projects/ANDROID/issues/ANDROID-15075?filter=allopenissues

Specs were updated according to the resolution in thread: https://teams.microsoft.com/l/message/19:9d2d0d5e2fb6472bb80f534bd702cf20@thread.tacv2/1723131635422?tenantId=9744600e-3e04-492e-baa1-25ec245c6f10&groupId=e265fe99-929f-45d1-8154-699649674a40&parentMessageId=1723131635422&teamName=M%C3%ADstica&channelName=design-appscore&createdTime=1723131635422&ngc=true
