### ISSUE TITLE
Mosaic component

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1556]
## Description
Evolve Mosaic component definition from Novum design team and include it in Mística Core.

## Tasks

- [x] [Update specs](https://www.figma.com/file/jQK3SDynSEq8H3ekuYd7u0/Vertical-Mosaic?type=design&node-id=1%3A462&mode=design&t=1oOZIVt0K4XkcRQr-1)
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1670)

**Comment by aweell** [comment]
I leave here the initial exploration in order to find the best approach to "coretize" both vertical and horizontal mosaic extended components:

https://excalidraw.com/#json=4wc4tuDq6k1uV-mEN_OLU,4t0bvSSd6awWAJ9ERu5qIQ

The initial idea summarized:

* The vertical mosaic it will renamed as `mosaic` by default it has the same element ordering that the component actually has and it can be configured to have a vertical and horizontal directions. Each of them will have their own ordering logic, allowing to create the ordering proposal for the horizontal one also.
* The horizontal mosaic will be renamed as `mosaicCarousel` and it will reuse internally the `mosaic` component with the direction configured as horizontal.
* This approach allows not only to create a carousel buy also to reuse the mosaic component inside an horizontal scroll for example.
