### ISSUE TITLE
Loading Screen component

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1560]
## Description
This component will be included in Mística Core but we need to change the current specification to be adapted with global needs

- Custom timings for animations (for in/out & loops)
- Custom assets per brands
- Desktop design

https://www.figma.com/file/Via0lhrPKYB6DOQMbWcshO/Loading-animation?type=design&node-id=1%3A3&mode=design&t=VysBEXB52Zk0UiAV-1

## Tasks

- [x] Create specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] Web [ticket](https://jira.tid.es/browse/WEB-1661)

**Comment by AnaMontes11** [comment]
Las specs incluyen definición para:

- BrandLoadingScreen
- LoadingScreen (pausado por el momento)
