### ISSUE TITLE
Movistar color accessibility

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1568]
## Description
Include new definition about colors with improvements in accessibility

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [x] Android ticket
- [x] iOS ticket
- [x] Web ticket

## Dependencies
- [ ] https://github.com/Telefonica/mistica-design/issues/1700
- [x] https://github.com/Telefonica/mistica-design/issues/1733
