### ISSUE TITLE
Icon Button evolution

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1601]
### Description

Evolve icon button to support current system cases & new requested use cases.

### Actual cases

| Element | Example | Replacement |
|--------|--------|--------|
| DataDisplay Inverse | ![Screenshot 2024-02-06 at 09 49 22](https://github.com/Telefonica/mistica-design/assets/44420072/6ca5ca33-7c45-47de-b49f-15c09a51becc) | variant = `default`, size = `small`, theme = `inverse` |
| DataDisplay Default (+ Data, Highlighted) | ![Screenshot 2024-02-06 at 09 52 06](https://github.com/Telefonica/mistica-design/assets/44420072/7abda6c0-f1e0-4bd7-8883-6193353d900a) | variant = `default`, size = `small`, theme = `default` |
| Popover | ![Screenshot 2024-02-06 at 09 57 45](https://github.com/Telefonica/mistica-design/assets/44420072/464fa1de-e63f-43e9-b201-f17c7c96615b) | variant = `default`, size = `default`, theme = `default`|  |
| Callout | ![Screenshot 2024-02-06 at 09 58 12](https://github.com/Telefonica/mistica-design/assets/44420072/79eae857-2a78-4d61-898b-ca433879d186) | variant = `default`, size = `default`, theme = `default`|  |
| Modals | ![Screenshot 2024-02-09 at 14 43 10](https://github.com/Telefonica/mistica-design/assets/44420072/bcacf141-dd6a-4ddd-974e-bad2daa560aa)| variant = `default`, size = `default`, theme = `default`|  |
| Search field | ![Screenshot 2024-02-12 at 13 57 19](https://github.com/Telefonica/mistica-design/assets/44420072/850afcb3-d3bb-47ca-b6db-13d3b22875e0) | variant = `default`, size = `default`, theme = `default`|  |

### Tasks

 - [x] Update specs
 - [x] Design documentation
 - [x] Add to mobile library
 - [x] Add to desktop library
 - [x] Add to UI Kit
 - [ ] Android ticket
 - [ ] iOS ticket
 - [x] [Web ticket](https://jira.tid.es/browse/WEB-1722)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1554

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** November  7, 2023</sup>
### Goal

Avaliar a proposta de adicionar states no componente Icon Button

### Context

Na tab de Casa Inteligente, vamos aplicar o Icon Button como um slot no componente Boxed Row, com isso, precisamos confirmar se existe a possibilidade de criar os estados para o componente, pois no Figma, não está disponível.

- Default
- Selected
- Disabled
- Loading

### Impact

Aplicando essa evolução proposta, não precisaríamos criar uma variação do componente Icon Button na biblioteca Vivo Extended.

### Discussion Questions

ND

### Do you have a visual proposal?

https://www.figma.com/file/FO2rWBWMWFrtSvazuuS0If/Evolu%C3%A7%C3%A3o-Icon-Button?type=design&node-id=1%3A86&mode=design&t=lS5m9nLj4KE5CBRV-1</div>

**Comment by yceballost** [comment]
debería ser el accordion otro caso más?
- Carousel controls?
- Counter? (me suena de haber dicho que ese caso era especial)
- Search field
- Select?
- Dismiss de la snackbar
- Play/Pause video en cards
- Checkbox/radio? 😬 Es otra tarea diferente pero deberíamos de tener el área minim de 48
- CVV

**Comment by AnaMontes11** [comment]
En los header de los accordion, al ser todo el área touchable tendríamos que revisar cómo sería el comportamiento de los estados.

> debería ser el accordion otro caso más?
> 
> * Carousel controls?
> * Counter? (me suena de haber dicho que ese caso era especial)
> * Search field
> * Select?
> * Dismiss de la snackbar
> * Play/Pause video en cards
> * Checkbox/radio? 😬 Es otra tarea diferente pero deberíamos de tener el área minim de 48
> * CVV

En los header de los accordion, al ser todo el área touchable tendríamos que revisar cómo sería el comportamiento de los estados.

**Comment by aweell** [comment]
Accordion, dateField, Select, Search...justo como comenta @AnaMontes11 no llevarían el icon button porque el elemento interactivo es todo el contenedor, ahí simplemente va un icono

**Comment by yceballost** [comment]
El search field tiene la "X" para borrar el contenido, ahí si debería llevar icon button
