### ISSUE TITLE
Change LoadingBar color in vivo new 

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1606]
https://jira.tid.es/browse/OBVIVO-2243

## Description
Change to vivoPurple and vivoPurple10

## Tasks
- [x] Add to vivo new library
- [x] Android update tokens
- [x] iOS update tokens
- [x] Web update tokens
