### ISSUE TITLE
Sheet dismiss (A11y)

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1610]
## Description

Vivo reports that users of assistive technologies get stuck in the sheet if they want to close it.

It is necessary to verify that there is no native way to close the sheet so that a solution is sought if necessary.

![Screenshot 2024-01-09 at 11 41 43](https://github.com/Telefonica/mistica-design/assets/44420072/fce84383-8bd9-49ae-940e-52b19fe2c166)

## Tasks

- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-14154)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-9663)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1692)

**Comment by aweell** [comment]
Closed as solved https://github.com/Telefonica/mistica-ios/pull/335
