### ISSUE TITLE
Use barTrack token in progressBar, Stepper & Slider

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1615]
https://jira.tid.es/browse/OBVIVO-2243

## Description
Replace control token to barTrack in progressBar, Stepper & Slider

## Tasks

- [x] Update specs
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add token to tokens file
- [x] Add to brand libraries
- [x] Android PR
- [x] iOS PR
- [x] Web PR
