### ISSUE TITLE
Split tag tokens

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1627]
## Description
Create new tokens to have more flexibility to manage tags by brands

## Tasks

- [x] Update specs
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Update skin jsons
- [x] Add tokens to brand libraries
   - [x] Telefónica
   - [x] Movistar
   - [x] Blau
   - [x] o2
   - [x] TU
   - [x] Vivo
   - [x] Vivo new
- [ ] Check UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1784)
