### ISSUE TITLE
Badge without Border

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1642]
## Description
Actualmente el `border` en el `badge` interesa en dos ocasiones:

- cuando lleva un children
- cuando va sobre un fondo inverse

Vemos necesario abrir la posibilidad de que el componente `badge` pueda no llevar `border` por ejemplo, cuando va dentro de una `tag`.
Para evitar tener una prop `border` True/false se decide como solución forzar el comportamiento dependiendo de si tiene children o no.

**Issue relacionada con:** Tag Evolution (Add a Badge) #1625

## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1733)

**Comment by aweell** [comment]
Added withChildren configuration in Brand Factory's component example
