### ISSUE TITLE
Row List with slot + preset

### ISSUE THREAD

**Issue by AnaMontes11** [Telefonica/mistica-design#1653]
## Description
Habilitar tanto en las rows como en las boxed rows la posibilidad de usar el slot con cualquier preset (navigation, checkbox, radio, switch...)

## Tasks

- [x] Update specs
- [ ] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1777)

## Discussion
https://github.com/Telefonica/mistica-design/discussions/1647

**Comment by aweell** [comment]
We hide the slots in the resources/Zone C - Presets until this was developed, the ticket is already closed and working, so I moved this issue to milestone 14.3.0
