### ISSUE TITLE
Buttons positioning in ButtonLayout

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1674]
### Tasks

- [x] Update specs
- [x] [Add to mobile library](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/ri3XWVh6fBRLBHDSH8uBZb/M%C3%ADstica-Mobile?type=design&mode=design&t=gBD9brOljk2UOVCE-1)
- [x] Add to desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1763)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/680

<div type='discussions-op-text'>

<sup>Originally posted by **yceballost** August  9, 2022</sup>
Actualmente el posicionamiento del ButtonLayout es de esta forma:
![image](https://user-images.githubusercontent.com/6722153/183633109-a4f6b945-73e0-439f-81ba-1155a0fb59fd.png)

Deberíamos posicionar el primary a la izquierda, de manera contrario a lo actual?

@aweell plantea que según dónde se alinee el buttonLayout puede invertir su orden. 
Si las acciones de un dialog van a la derecha, el orden sería:
Link < Secondary < Primary

Si las acciones se posicionan en la izquierda
Primary > Secondary > Link</div>
