### ISSUE TITLE
Update Naked Card padding right

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1686]
### Tasks

- [x] Update documentation
- [x] Update mobile library
- [x] Update desktop library
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://github.com/Telefonica/mistica-web/pull/1040)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1676

<div type='discussions-op-text'>

<sup>Originally posted by **BiancaMach** February 23, 2024</sup>
### Goal

Avaliar a possibilidade de inserir um padding-right no bloco de componentes de texto no Naked Card para ter maior área de respiro no carrossel.

### Context

Atualmente, quando há mais de um card, o espaçamento utilizado não dá respiro suficiente para os blocos de texto, sendo assim necessário inserir um padding-right para que essa área de respiro seja maior.

### Impact

Em situações onde há grande quantidade de texto, a área de respiro maior deixará a leitura mais acessível.

### Discussion Questions

Como está atualmente:
<img width="730" alt="Screenshot 2024-02-23 at 16 38 57" src="https://github.com/Telefonica/mistica-design/assets/153837409/dbec78e9-3cbd-4a70-84cf-51bcc719a667">

<img width="735" alt="Screenshot 2024-02-23 at 16 39 12" src="https://github.com/Telefonica/mistica-design/assets/153837409/db9ba9eb-1889-402a-8d2d-62af71d7406c">

### Do you have a visual proposal?

https://www.figma.com/file/tmIfzrqKmIUellqazmapgs/Update-Naked-Card?type=design&node-id=331%3A5823&mode=design&t=KzAdyypowLLAASrp-1</div>
