### ISSUE TITLE
Update components with iconButton

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1688]
## Description

- [x] Callout (8)
- [x] Highlighted card (8) 
- [x] Dialog + Sheet (16) 
- [x] Popover (8)

(*) Snackbar and counter will use a custom solution

## Tasks

- [x] Update specs
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1765)
