### ISSUE TITLE
Subtitle color consistency across components

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1699]
- Accordions
- Lists
- Snap cards

### Tasks

- [x] Update specs
- [x] Update mobile library
- [x] Update desktop library
- [x] [iOS ticket](https://github.com/Telefonica/mistica-ios/pull/343)
- [x] [Android ticket](https://github.com/Telefonica/mistica-android/pull/337)
- [x] [Web ticket](https://github.com/Telefonica/mistica-web/pull/1046)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/848

<div type='discussions-op-text'>

<sup>Originally posted by **yceballost** October 14, 2022</sup>
Today is the day.

# Context
Now, rowlist subtitles are using textSecondary as a color but in cards subtitle color is textPrimary
![image](https://user-images.githubusercontent.com/6722153/195828937-90ed7a3c-1886-4119-b643-d23bea73501d.png)
![image](https://user-images.githubusercontent.com/6722153/195829005-2da4fc4d-09a3-49bf-82fb-9a00fb933b23.png)

# Problem
Inconsistency in subtitles between components (rowlist and cards)
Should we modify the rowlist subtitle color to keep consistency with the subtitle hierarchy across the different components?

# Proposal
Use textPrimary in rowList subtitles

</div>
