### ISSUE TITLE
displayCardGradient token

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1701]
## Description

With the new brand definition O2 will start using a different colors in the display card gradients. In order to keep the definition i all brands but o2 we need to tokenize the gradient.

The current definition:

`linear-gradient(180deg, rgba(0, 0, 0, 0) 0%, rgba(0, 0, 0, 0.4) 29.02%, rgba(0, 0, 0, 0.7) 100%)`

The new o2 definition  (WIP in https://github.com/Telefonica/mistica-design/issues/1689):

`linear-gradient(180deg, rgba(0, 80, 255, 0) 0%, rgba(0, 80, 255, 0.6) 29.02%, rgba(0, 80, 255, 1) 100%)`

With the new gradient definition:

```
"cardContentOverlay": {
    "type": "linear-gradient",
    "value": {
        "angle": 180,
        "colors": [
            {"value": "rgba({palette.beyondBlue}, 0)", "stop": 0},
            {"value": "rgba({palette.beyondBlue}, 0.4)", "stop": 0.3},
            {"value": "rgba({palette.beyondBlue}, 0.7)", "stop": 1},
        ],
    },
    "description": "beyondBlue"
},
```

## Tasks

- [x] [Update specs](https://www.figma.com/file/tKdPOfcUALzVIh5oizFbm7/branch/UzQu1uw1nnwekGLsTwhV1Q/%F0%9F%94%B8-Cards-Specs?type=design&node-id=1373%3A2728&mode=design&t=uCypHgtUVTgeydUY-1)
- [x] Update brand libraries
- [x] [Add to mobile library](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/LlaDt0YUgh6CvWvctvAQST/M%C3%ADstica-Mobile?type=design&mode=design&t=fdqdSvSI0KBEZ67s-1)
- [x] [Add to desktop library](https://www.figma.com/file/DSWhPLyJzbliP1fBrLxDUR/branch/FKRiA2npa2P8tqTlwccvOT/M%C3%ADstica-Desktop?type=design&mode=design&t=4G63OXuc1i11GC8K-1)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1799)

**Comment by yceballost** [comment]
0.29 could be 0.3 to round this number...? 😬

**Comment by aweell** [comment]
Yes, i donno why is 29.02% in production
