### ISSUE TITLE
Heading level in components

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1716]
## Description
Include in specs file the possibility to change heading level for headers, cards and hero components

## Tasks
- [x] Update specs
   - [x] [Hero](https://www.figma.com/file/M8t65SWdTUyM44YjxuzCyu/branch/s5qkAjrDPBYLEkEkAVK2wx/%F0%9F%94%B8-Hero-Specs?type=design&mode=design&t=RuNc9ISVBOG7ZHEP-1)
   - [x] [Cards](https://www.figma.com/file/tKdPOfcUALzVIh5oizFbm7/branch/W7QvDXtn9gzJsV5H3EXATW/%F0%9F%94%B8-Cards-Specs?type=design&mode=design&t=4qn4qltUB9g7rgIy-1)
   - [x] [Headers](https://www.figma.com/file/Xm3r8nRNlbAiZNlkaH5YX1/branch/bFEVMQE61CCOde581DaFom/%F0%9F%94%B8-Header-Component-Specs?type=design&mode=design&t=1NIp7xONQGeEL7gJ-1)
   - [x] [Callout](https://www.figma.com/file/LzhzNPzE8nY9d7Yvo10d5d/branch/6tA2bHHm0eR4u2ToTUJcE7/%F0%9F%94%B8-Callout-Component-Specs?type=design&mode=design&t=acwV7wD89dEbD371-1)
   - [x] [Lists](https://www.figma.com/file/Be8QB9onmHunKCCAkIBAVr/branch/B9g9a38Qy40U1vSLRlbYdL/%F0%9F%94%B8-Lists-Specs?type=design&mode=design&t=9CVy5RAG1KbDjswL-1)
   - [x] Accordions
   - [x] Empty state
   - [x] Empty state card
   - [x] navigation bar
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1796)
