### ISSUE TITLE
Weight text style for snap and nakedSmall (Only Figma)

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1720]
## Description

In order to show the titles medium in both components we need to create a new text style named cardTitleSmall

size = textPreset2
weight = cardTitle

## Tasks

- [x] [Update specs](https://www.figma.com/file/tKdPOfcUALzVIh5oizFbm7/branch/UJNg9eBsXPsX368b1KMou9/%F0%9F%94%B8-Cards-Specs?type=design&node-id=1373%3A3267&mode=design&t=0QeusRoJRAD1b42r-1)
- [ ] Design documentation
- [x] [Add to mobile library](https://www.figma.com/file/WCkDDzlXE16R6yXaljxddj/branch/rOyYBEZPEdywqcPtkNyAB3/M%C3%ADstica-Mobile?type=design&node-id=0%3A661&mode=design&t=Q8fuqFfGWIeKyzXJ-1)
- [x] [Add to desktop library](https://www.figma.com/file/DSWhPLyJzbliP1fBrLxDUR/branch/cUS31ZmXMOrjh8GtBNyXdp/M%C3%ADstica-Desktop?type=design&mode=design&t=TIpvDYfSAbet6XG1-1)
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://github.com/Telefonica/mistica-web/pull/1046)
