### ISSUE TITLE
Custom asset for buttonLink chevron in Vivo New

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1725]
## Description
Use custom asset only for Vivo New skin

## Tasks

- [x] [Update specs](https://www.figma.com/file/koROdh3HpEPG2O8jG52Emh/%F0%9F%94%B8-Buttons-Component-Specs?type=design&node-id=4779-15738&mode=design&t=gW2Kny58bPsUZDTs-4)
- [ ] Add to mobile library
- [ ] Add to desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1809)

**Comment by yceballost** [comment]
We will implement this custom chevron with variables in Figma enterprise
