### ISSUE TITLE
Split control tokens (Chips, input labels, textTabBar)

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1733]
Create new two tokens:
- TextBrand
- TextActivated

_________________

* `textActivated` will replace → `textAppBarSelected` (Icon is `controlActivated`, text is `textActivated`)
* `textActivated` will replace usage of `controlActivated` in input labels and chip label
* `textBrand` new token to use in Avatar elements (w/ initials)
* `textBrand` new token to use in StackingGroup elements (+2)

### Tasks

- [x] Update inputs specs
- [x] Update chip specs
- [x] Update avatar specs
- [x] [Update stepper specs](https://www.figma.com/file/YIQIeK0R4bQNNkw2Friv6b/branch/oykbHPsGsQ2oBaWrCgfii2/%F0%9F%94%B8-Stepper-Component-Specs?type=design&node-id=0%3A248&mode=design&t=JImaHEOPccZvGOSE-1)
- [x] [Create tokens](https://github.com/Telefonica/mistica-design/pull/1756)
- [x] Update brand libraries
  - [x] Movistar
  - [x] Blau
  - [x] Telefonica
  - [x] O2
  - [x] O2 New
  - [x] Vivo
  - [x] Vivo New
  - [x] Tu
- [ ] iOS ticket
- [ ] Android ticket
- [x] [Web ticket](https://github.com/Telefonica/mistica-web/pull/1105)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1695

<div type='discussions-op-text'>

<sup>Originally posted by **HectorSancho** March  8, 2024</sup>
### Goal

Detach the control and activated control tokens and create two new tokens to better control the style in components such as chips and text fields.

Tokens proposal:

- textActivated
- borderActivated

### Context

In the current definition we do not have much control over the color of these tokens, as they have dependencies with other components. It especially impacts on dark modes

### Impact

Improve color definition in dark modes and be able to detach color styles from chips and other components of control tokens

### Discussion Questions

is it necessary?

### Do you have a visual proposal?

_No response_</div>

**Comment by aweell** [comment]
In inputs I also changed the definition of the label text when the field has error to `textError` and the helperText when is over inverse to `textErrorInverse`

Update: https://github.com/Telefonica/mistica-web/pull/1125
