### ISSUE TITLE
Mística Training

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1736]
## Description
Include new material file in Mística Materials with the goal to have a document to train with Mística
https://www.figma.com/file/PlHcR3HP6bqCStrqbjGVPp/M%C3%ADstica-Training?type=design&node-id=1%3A14&mode=design&t=JrZhWofBVe0ACmrW-1

The idea has already raised but needs time to improve the content

## Tasks

- [ ] Improve Mística Training file
- [ ] Design documentation access
- [ ] Add to Mística Material folder in Figma
