### ISSUE TITLE
→ Accessibility: Components | Callout

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1759]
### Description

- [x] The current component has the possibility to change its title tag between `h1` - `h6` is needed to allow also `<span>` or `<p>` tags
- [x] Tratar ordem de leitura
- [ ] Incluir label default do botão de dispensar ("Fechar informação" para Vivo). This is covered by https://jira.tid.es/browse/PRODUCTDSN-2541 

https://jira.tid.es/browse/OBVIVO-2636

## Tasks

- [x] Update component specs
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10464)
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-15018)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1952)

**Comment by yceballost** [comment]
@aweell heading feat was covered in this issue, right? https://github.com/Telefonica/mistica-design/issues/1716 Can you confirm?

**Comment by aweell** [comment]
Title as a span was covered in https://github.com/Telefonica/mistica-web/pull/1170

**Comment by aweell** [comment]
> Incluir label default do botão de dispensar ("Fechar informação" para Vivo).

This is covered by https://jira.tid.es/browse/PRODUCTDSN-2541
