### ISSUE TITLE
New O2 Academy icons

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1761]
## Description
Add new icons included in brand factory

- no-tickets
- no-photo-camera
- ear-plug
- smiley-happy
- no-smoking
- silence
- pickpockets

## Tasks

- [x] Add to icons library
- [x] Add to mistica-icons repo
- [x] update web icons

**Comment by yceballost** [comment]
I will close this ticket and we will include the icons in mistica-web with future icons because this icons is not a priority
