### ISSUE TITLE
OverMedia Context

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1764]
## Description
Fix some components when is over images/video

- [x] [Buttons](https://github.com/Telefonica/mistica-design/issues/2233)
- Boxed
- Text
- TextLink
- Timer

## Tasks

- [ ] Update specs
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Web ticket

**Comment by aweell** [comment]
Test to avoid contrast issues in text: https://www.figma.com/design/bAqgnJmC1ROqbiQVYg27jL/POC---Text-overMedia?node-id=0%3A1&t=VO3FvVhbORtKmDrZ-1

**Comment by yceballost** [comment]
Web included Over Media context in implementation with this assumption: "by the moment, all over media component will behave as inverse context until specs are updated"

We need to check all the component in this context, but i found some cases:
- Skeletons (now is showing with blue background (movistar p.e))
- Avatar (?)
- Slider
- Progress bar

**Comment by yceballost** [comment]
@aweell is it done, right? close?

**Comment by aweell** [comment]
Only for buttons, some components here still lack over media definition. I'll update this when completed

**Comment by aweell** [comment]
Buttons issue: https://github.com/Telefonica/mistica-design/issues/2233
