### ISSUE TITLE
Update chevron definition in lists

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1767]
## Description
Update specs to show the correct definition for chevron possibilities

## Tasks

- [x] [Update specs](https://www.figma.com/file/Be8QB9onmHunKCCAkIBAVr/branch/TpL8lD2tWiKCeGxEoqA1WV/%F0%9F%94%B8-Lists-Specs?type=design&node-id=0%3A1&mode=design&t=PP1KnJZcDdMubpxs-1)
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1549)
