### ISSUE TITLE
Headline (tag) in Headers

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1783]
### Description

Allow the possibility to have a tag in header component.

### Tasks

- [x] U[pdate specs](https://www.figma.com/design/Xm3r8nRNlbAiZNlkaH5YX1/branch/ySgCoh1CsqIJ7bcapzbKpU/%F0%9F%94%B8-Header-Component-Specs?m=auto&node-id=1649-10003&t=ZgF6iDuKrRBjSpqq-1)
- [x] [Update mobile library](https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/branch/ywiIgMbgL0AahHTQ3r1355/M%C3%ADstica-Mobile?m=auto&t=qDrF6H0nOQQ5Obuv-1)
- [x] [Update desktop library](https://www.figma.com/design/DSWhPLyJzbliP1fBrLxDUR/branch/6yoKj5dphDz65UwlKmM6or/M%C3%ADstica-Desktop?m=auto&t=AwCnOf8Lx0JBM2eH-1)
- [x] [Update component documentation](https://brandfactory.telefonica.com/document/1846#/components/header)
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1940)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1775

<div type='discussions-op-text'>

<sup>Originally posted by **JoseTelefonica** May 16, 2024</sup>
### Goal

I would like to have a headline (tag) in headers. We need to continue the experience throughout the app.

### Context

I am creating the bill flow in My O2 and trying to make the same experience throughout the app. If users see an tag with the bill status in some screens, when they land on the bill details, they don't see the same visual representation of this information.

### Impact

Create an option in Headers to show a headline (tag)

### Discussion Questions

Could we have this option in headers?

### Do you have a visual proposal?

https://www.figma.com/design/qKsUe3xW8wDOoySLOzWw3I/My-O2-App-Master-2024?node-id=233-5713&t=mv3c5PBZEsmmDjmT-4</div>
