### ISSUE TITLE
Aria-label in dismiss buttons

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1784]
## Description
Make possible to use aria-label in dismiss buttons.

- [x] [Popovers](https://www.figma.com/design/gmcy7hwB9WXxqT05jBnA3W/branch/aDvxH6K9U22A5g4wv0Lxtb/%F0%9F%94%B8-Popover-Specs?m=auto&node-id=1863-1253&t=729x28buidisTri2-1)
- [x] [Snackbar](https://www.figma.com/design/yCHLIfy4WMfRdlADwyL4kZ/branch/3s7gfSBHSC1JiCDJKhx41G/%F0%9F%94%B8-Snackbar-Specs?m=auto&node-id=2182-326&t=oJs2FDIUGV7b8OlW-1)
- [x] [Callout](https://www.figma.com/design/LzhzNPzE8nY9d7Yvo10d5d/branch/2SnhNVGChNFEE0UB8XGvZh/%F0%9F%94%B8-Callout-Component-Specs?m=auto&node-id=2558-3181&t=Gg4Bc85I9YCjsyXc-1)
- [x] [Chips](https://www.figma.com/design/512a5Ke4EldL0GYffCXGCJ/branch/Kx1mTkopsZo3YRjHtWkvnQ/%F0%9F%94%B8-Chips-Specs?m=auto&node-id=2091-1883&t=e4PQZHKQXQUwTfV8-1)
- [x] [Modals](https://www.figma.com/design/8TXIyWTJ8plJ06i1qwv97k/branch/IBI7n2JxXYq7jsB2m1mnUv/%F0%9F%94%B8-Modals-Specs?m=auto&node-id=2495-704&t=EpeCun32sBdOFbuw-1)
- [x] [Cards](https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/branch/pArEzcgxyEMvdvg5YhCpvg/%F0%9F%94%B8-Cards-Specs?m=auto&node-id=9507-6893&t=CuRDhfUNAPOdqkdJ-1)
- [x] [Sheet](https://www.figma.com/design/nxToAYk7FGC86TS0mY61TU/branch/SZ1U2jytVNvJmnSZ8YwjGV/%F0%9F%94%B8-Sheet-Specs?m=auto) 

The purpose of this change is to enable adding more context about what the user is closing when the dismiss button is focused by AT.

## Tasks

- [x] Update specs
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-15020)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10466)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1966)

**Comment by aweell** [comment]
Cards already allow to pass a "label" to the top actions: [example](https://mistica-web.vercel.app/playroom/#?code=N4Igxg9gJgpiBcIA8ARAlgZwA4BsCGAningC54DCeATlADoB2ABI2pPQLzAPPNLlpUwOGIwxoAXjE4AWAAwBfRgCM8YANYBzKhACu9KOQg4IVTpGNUMAOiVU8%2BgDIQA7vIB83HrwCSbb-QA3CFYYAAV8egAxNGEAJRgNHXwqRnMTMyMTa1t7KEUAeg8mHiR8-kFhIuZ5TwALGDwoHDR6KWAkABU8DUYSAiwpWhAsbQBbCCG3AAkGppaYUq6NNxrikZgSNBJhdiHQqg2t4SHPTe3BkA6jmBPi2AwwKjQsTYgOIZQYB6eXtDfb5hKHQkEhvTieXgAIWBoPo%2BzQo2oBFEiJwOEYtQOADNdiBaiCsBh4Pl8hoIBANMIrJBRpMITwAIJgV70emlaEgt7wxFUAhVRirZhvcjGDBtAAUAEpGOw3IxgPJBYxVCyMJwANr0rjFLy%2BN7wRh6%2BgONAafH0FoaeKJZIAGnpQrhBwwRMYUplcoV9p1PHwShgOANQxNZpIFvoGiG3q88mjPG1XmYYHq6hgUH2EEJBoTieYRoNRoAymQqNE0Wm47m-QGg%2BAU2o0wDE7GHYw9MmYKn09os-LW3m2AW2MXqNaktRK4nq4HGEN2-XGyBJ9Vl4xYFi8EkSOQF1ADRucGLV8LavYNDADe7ZfKWz7b8wALqrQoMJcgEj1UZfBDqy4BmBYm8rB4CAD62iAzhoFAH4YD%2BADMABssi2gAjIhAAcT5AA)
