### ISSUE TITLE
→ Accessibility: Components | Snackbar

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1795]
### Description

The proposed behaviour for this component is:

* Announce the message but do not move the focus automatically
Do not trap the focus on the snackbar, allow the user to access or exit its content
* If the snackbar presents relevant actions (other than dismiss), make it persistent so that the user can access its content at any time
* If the snackbar has no relevant actions or the action is a dismiss, it can appear for a certain time and autodismiss since its content has already been announced to the user

Here are the resources mainly from where this information has been obtained:
https://m3.material.io/components/snackbar/accessibility
https://www.magentaa11y.com/checklist-native/snackbar-toast/

### Tasks

- [x] [Update specs](https://www.figma.com/design/yCHLIfy4WMfRdlADwyL4kZ/branch/t8dD4AbxCcNh9lEU4hLWLh/%F0%9F%94%B8-Snackbar-Specs?m=auto&node-id=0-1&t=XPqJr9nnJK6Sn2Uo-1)
- [ ] Design documentation
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-13687)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10221)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1889)
