### ISSUE TITLE
Title2 component (remap titles)

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1796]
## Description
Create new title between 2 and 3. This cause a breaking change in dev side.

Title remapping:

- Title1 → no change
- Title2 → the new one
- Title3 → The old title2
- Title4 → The old title3

Title1 : 12px
Title2: 16px
Title3: 20px (Vivo: 18px)
Title4: 24px

## Tasks

- [x] [Update specs](https://www.figma.com/design/yQRVCOmRQNM98bnXndLPxK/branch/2cloOSd6QkwcsyF7MpCkkw/%F0%9F%94%B8-Title-Specs?m=auto&t=tVmcREIFD6J97XcB-1)
- [ ] Design documentation
- [x] Update brand libraries
   - [x] Movistar
   - [x] Movistar Classic
   - [x] Blau
   - [x] O2 new
   - [x] O2
   - [x] Telefonica
   - [x] Vivo
   - [x] Vivo-new
   - [x] Tu
   - [x] Roboto | Movistar
   - [x] Roboto | O2 | Vivo | Telefónica | Blau
   - [x] OnAir Font
   - [x] OnAir Font (o2)
   - [x] Vivo Type
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-15048)
- [x] i[OS ticket](https://jira.tid.es/browse/IOS-10491)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1982)

**Comment by paulasuarezb** [comment]
discussed here -> https://github.com/Telefonica/mistica-design/discussions/1486

**Comment by aweell** [comment]
Estrategia de cambio:

* Actualizar librerías de marca:  renombrar title2 a 3. Crear un token title2 con la definición de peso = actual title2. Mergear y publicar las librerías de marca. 
* Actualizar librerías de figma: Crear un nuevo title2 y los antiguos renombrarlos uno para arriba
* Actualizar los tokens JSON de marca renombrando title2 por title3.
* Crear token de peso para title2 y definir que pesos son los adecuados para cada marca ya que en algunas actualmente es light y no parece adecuado para un texto de 16px
* En desarrollo además de cambiarle el nombre al componente title2 por title3 tendrán que cambiar el nombre de los tokens a title3 para que esos cambios de tamaño y line-height entre vivo-new y el resto sigan aplicando. Vease: el nuevo title3 en todas será de 20px menos en vivo que es de 18px (solo mobile)
El nuevo title 2 es para todas 16px mobile /  18px desktop, por lo que no tiene tokens ni de size ni line height
