### ISSUE TITLE
→ Accessibility: Components | Lists | Group info

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1801]
## Tasks

- [x] Add a11y specs to lists

* Allow aria-label when the list is type informative
* Add detail to content grouping when has controls

https://jira.tid.es/browse/OBVIVO-2632

- [x] [Update specs](https://www.figma.com/design/Be8QB9onmHunKCCAkIBAVr/branch/FWBijxKTDR3kEA1raf8owC/%F0%9F%94%B8-Lists-Specs?m=auto&node-id=4615-10677&t=06TTg9oUaCdZuPJH-1)
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-14884)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10448)
- [x] [Web ticket ](https://jira.tid.es/browse/WEB-1955)

**Comment by spairbierzo** [comment]
Justo to double check, are we going to need a ticket for iOS as well, @yceballost?

**Comment by yceballost** [comment]
@aweell is there any reason why a ticket wasn't created?

**Comment by aweell** [comment]
@spairbierzo, @yceballost, there is no other reason beyond not finding the ticket that referred to this bug in iOS. If it doesn't exist, I'll create it.

**Comment by spairbierzo** [comment]
Yep, I reckon it doesn't exist for iOS, thanks @aweell !

**Comment by aweell** [comment]
> Yep, I reckon it doesn't exist for iOS, thanks @aweell !

Here https://jira.tid.es/browse/IOS-10448

**Comment by spairbierzo** [comment]
Cheers man! Noted ;)
