### ISSUE TITLE
Add brandLoadingScreen themeVariant token

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1807]
## Description

In order to provide an accessible color combination for all brands we found necessary to determine via skin when the brandLoadingScreen is inverse or not. This will be defined in each brand skin under a new category "themeVariant":

```
"themeVariant" : {
     "brandLoadingScreen" : {
              "value" : "default" | "inverse" | "alternative" 
}
```

## Tasks

- [x] [Update specs](https://www.figma.com/design/KYdCKU8obcDapI8ihpsaWs/branch/Nzd1eImF4KJmeck58Rr92g/%F0%9F%94%B8-LoadingScreen-Specs?m=auto&t=cpkKaugZGktSKp3e-1)
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Add to UI Kit
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-15966)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-11218)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2234)
