### ISSUE TITLE
→ Accessibility: Components | Include span as a valid tag for cards title

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1827]
### Description

https://github.com/Telefonica/mistica-web/issues/1167

- [x] Update the card specs to allow span as a valid tag for card titles

### Tasks

- [x] [Update specs](https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/branch/7ZEeDziwqAqLsUOpXvYGNp/%F0%9F%94%B8-Cards-Specs?m=auto&t=RVvUUZQw8rKh5EJa-1)
- [x] [Web ticket](https://github.com/Telefonica/mistica-web/issues/1167)
