### ISSUE TITLE
Table | Header rows in any column

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1829]
## Description

* Es válido que un header row no esté necesariamente en la primera columna: https://www.w3.org/WAI/WCAG21/Techniques/html/H63
* Podemos argumentar que cambiar la posición de los elementos es un fallo de esta técnica: https://www.w3.org/WAI/WCAG21/Techniques/css/C27
* Sin embargo, al estar etiquetado como header row, esta información es leída al inicio de cada row, incluso antes del primer elemento de la columna 1 (o las columnas que haya delante), manteniendo su significado. Por lo que me cuesta afirmar que sea un fallo de https://www.w3.org/WAI/WCAG21/Understanding/meaningful-sequence

## Tasks

- [x] [Update specs](https://www.figma.com/design/WtF16bfvE9kKS4yx3VtLuE/%F0%9F%94%B8-Table-Specs?m=auto&t=mcZHVNAwa2CuBrCz-1)
- [x] Update mobile library
- [x] Update desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-1948)
