### ISSUE TITLE
Navigation Bar menu

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1836]
## Tasks

- [x] Update specs
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2056)
