### ISSUE TITLE
Side Drawer

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1880]
## Tasks

- [x] BF documentation
- [x] [Design specs](https://www.figma.com/design/NfM16IJ4ffPVEdiFbtU0Lu/%F0%9F%94%B8-Drawer-Specs?node-id=10-5397&t=7EsWeXtPVlshi13L-1)
- [x] [Desktop library](https://www.figma.com/design/DSWhPLyJzbliP1fBrLxDUR/branch/Fo8DdbT58srBm6huBwNJSi/M%C3%ADstica-Desktop?m=auto)
- [x] [Mobile library](https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/branch/XO8uEzBpYhtssyRosQV3CQ/M%C3%ADstica-Mobile?m=auto&node-id=48528-2384&t=BizF5tL5vsTK924S-1)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2113)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/1835

<div type='discussions-op-text'>

<sup>Originally posted by **annefranca** July 26, 2024</sup>
### Goal

Discutir e avaliar a proposta de adicionar o componente Side Drawer em Mística.

### Context

Como conversado em nossa reunião semanal, começamos a desenvolver o Side Drawer na biblioteca Extended para o projeto Web Essential. O componente nasceu como Extended pelo prazo que tínhamos v/s o lançamento do MVP, com isso, gostaríamos de avaliar a possibilidade do Side Drawer pertencer a biblioteca Mística.

### Impact

Ao adicionar o Side Drawer padronizado como componente melhoraria a experiência da pessoa usuária, o tempo dos times de desenvolvimento e a consistência nas aplicações das jornadas e nos fluxos.

### Discussion Questions

ND

### Do you have a visual proposal?

https://www.figma.com/design/VL1iNAjAjyTk3EIaaDmCW4/Side-Drawer?node-id=8902-1250&t=8y9xW4hnYHBSzkZh-1</div>
