### ISSUE TITLE
Meter component

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1899]
## Description
New component in Mística

## Links 
Ticket UXW: https://jira.tid.es/browse/PRODUCTDSN-2785
Ticket LOC: https://jira.tid.es/browse/LOC-1699

## Tasks

- [x] Update specs
- [ ] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2079)
