### ISSUE TITLE
Remove divider in Advanced Data Card

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1902]
> [!NOTE]  
> Specs have to be updated by Vivo Team

https://jira.tid.es/browse/OBVIVO-2287

## Description

- Remove the divider that separates the slots. And a spacing of 32px between slots.
- Update Link button in component libs.

## Tasks

- [ ] Update specs (Vivo)
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Web ticket
