### ISSUE TITLE
Include new text and pretitle in Highlighted Value Block

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1903]
> [!NOTE]  
> Specs have to be updated by Vivo Team

https://jira.tid.es/browse/OBVIVO-2288
~https://jira.tid.es/browse/OBVIVO-2717~

## Description

- Add one more Text component to the Current SecondaryValue
- And as an extra, we are proposing a semantic improvement in the code.

## Tasks

- [x] Update specs (Vivo)
- [x] Add to mobile library
- [x] Add to desktop library
- [x] [Web ticket](https://github.com/Telefonica/mistica-web/pull/1329)
