### ISSUE TITLE
Switch upgrade to Material 3

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1917]
## Description

The current switches are using material 2 definition, upgrade them to material 3:

https://m3.material.io/components/switch/overview 

Related discussion: https://github.com/Telefonica/mistica-design/discussions/1551

## Tasks

- [x] Update specs
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [ ] Web ticket
