### ISSUE TITLE
Switch I|O labels in iOS 

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1918]
## Description

Web switches should show I|O labels when are inside an iOS webview and the setting is enabled in user preferences.

https://developer.apple.com/design/human-interface-guidelines/toggles

Related discussion: https://github.com/Telefonica/mistica-design/discussions/1551

## Tasks

- [x] Update specs
- [ ] Design documentation
- [ ] Add to mobile library
- [ ] Add to desktop library
- [ ] Add to UI Kit
- [ ] Android ticket
- [ ] iOS ticket
- [ ] Web ticket

**Comment by yceballost** [comment]
which is the _browser prefers_ to show this feature?

**Comment by aweell** [comment]
> which is the browser prefers to show this feature?

This is not targeting browser behaviour but web switches behavior inside an iOS webview when the user has I/O Labels enabled in his accesibility settings

**Comment by yceballost** [comment]
Mmm so, maybe is needed some configuration supported by the "bridge" to make possible this behavior, right? just curious
