### ISSUE TITLE
New icons in Telefónica set

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#1920]
## Description
[Icons.zip](https://github.com/user-attachments/files/17326297/Icons.1.zip)

we have other concepts like: 
- mude
- microphone
- video-camara

We need rename some icons, to have coherence with the rest of the concepts of other brands

## Tasks

- [x] Add to brand libraries
- [x] Add to mistica icons
- [x] Update web icons
