### ISSUE TITLE
→ Inverse | Slider

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#1936]
## Description

https://mistica-web.vercel.app/playroom/#?code=N4Igxg9gJgpiBcIA8AlGBnADhAduglgG4wAyAhgJ4QCuALgASFkBO%2BZOtAvADoj47Fm6GLwB83HPXpIAQhAAe9TGShR%2BAcwCanYABYAHAF9xkqdLRZcBYuSp0TZs0gDKAG3yxm9HGQC2MHhB0d09eel9%2BHQBGQ3CyeWiABljaCAhXWnxMegB6Bycci2w8IlJKGlp8pBy5eRNqoqtS2wqTEAAaEFoACxh-dAQAbRAZVzJqDpAAWQhCfHRaFkmAeQAmAH0AORgAd0mAFRhXGAAzXHwwMgOJzoA1Iggt3ZAAXU6djx6B%2BEGAZgA2RIvQxAA

The current color definition of the slider is not working in inverse

## Tasks

- [x] [Update specs](https://www.figma.com/design/UZHm7V3gO7nVnbf1b0Vj7b/branch/Oj3pvSsb0S0HzeJnTONJiB/%F0%9F%94%B8-Slider-Component-Specs?m=auto&t=YGB4HFOn26p4kkUd-1)
- [ ] Design documentation
- [X] [Add to mobile library](https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/branch/c0m5NK270PDIjzZyvqo4aY/M%C3%ADstica-Mobile?m=auto&t=RKLE5206RrJBqtEI-1)
- [x] [Add to desktop library](https://www.figma.com/design/DSWhPLyJzbliP1fBrLxDUR/branch/TMvB9XsnSp2E92BJHcvEnk/M%C3%ADstica-Desktop?m=auto&t=ROZqEHCUTG8WPa2Y-1)
- [x] [Android ticket](https://jira.tid.es/browse/ANDROID-15310)
- [x] [iOS ticket](https://jira.tid.es/browse/IOS-10643)
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2084)
