### ISSUE TITLE
Update the Naked card to toggle the visibility of the image.

### ISSUE THREAD

**Issue by andredelramo-hm** [Telefonica/mistica-design#1995]
## Description
- We need the card image to be toggleable (show/hide).
- When hiding the image, the Top Actions and the Asset (if visible) must be rearranged within the available space.
- When the card has no image, the theme context of the Top Actions and the Asset is defined by their own context.

## Tasks

- [x] [Update specs](https://www.figma.com/design/tKdPOfcUALzVIh5oizFbm7/branch/F58hHgn56kzoPgkP2JWYBH/%F0%9F%94%B8-Cards-Specs?m=auto)
- [x] [Add to mobile library](https://www.figma.com/design/WCkDDzlXE16R6yXaljxddj/branch/38x2oFmOWNrw1aXpvmTPdl/M%C3%ADstica-Mobile?m=auto)
- [x] Add to desktop library
- [x] [Web ticket](https://jira.tid.es/browse/WEB-2127)
