### ISSUE TITLE
Snackbar specs update

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#487]
## Description

The current Android snackbar component in Figma is not following the material specs. 

Material specs for reference:

![Screenshot 2022-06-22 at 11 29 56](https://user-images.githubusercontent.com/44420072/174995520-746e0131-bb06-45d0-871d-0ed8c78d7274.png)
![Screenshot 2022-06-22 at 11 30 11](https://user-images.githubusercontent.com/44420072/174995529-a49215d5-5741-4e21-8e96-a320b1d5de0e.png)

In order to be consistent between platform implementations, all components will be updated to have 8px `margin` between description and action.

## Tasks

- [x] ~Rename `Snackbar` to `Toast`~ #704
- [x] Update specs Figma Mobile library snackbar component
- [x] Update snackbar component specs file
- [x] Update current `margin` values in web implementation
- [x] Use text-presets in web implementation

**Comment by yceballost** [comment]
@aweell esa tarea de update current margin se llegó a hacer? sino, crear ticket a web pls y ponlo en el body marcando el check de eso
