### ISSUE TITLE
Data card Figma prop type

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#518]
### Discussed in https://github.com/Telefonica/mistica-design/discussions/515

<div type='discussions-op-text'>

<sup>Originally posted by **aweell** June 27, 2022</sup>
La implementación actual de la `dataCard` en web permite cambiar el tipo de asset entre los siguientes valores: `icon`, `image` o `none`

![Screenshot 2022-06-27 at 09 34 42](https://user-images.githubusercontent.com/44420072/175885109-c1a3f633-4647-404c-b4c0-8cc1243c7fd7.png)

Recientemente se ha añadido este approach a la `snapCard` donde nos encontramos con la misma prop:

![Screenshot 2022-06-27 at 09 36 25](https://user-images.githubusercontent.com/44420072/175885449-0f50434f-0ef0-40c1-a983-ed5715fee31d.png)

Debería la `dataCard` en Figma permitir este cambio aunque actualmente no aparezca contemplado dentro de sus specs?

</div>

**Comment by AnaMontes11** [comment]
**Tasks:**

- [x] Habilitar la prop image para que sea intercambiable con icon o None en el componente Figma 

--- 

- [x] Mobile 
- [x] Desktop

---

- [x] Actualizar Specs Data Card.
- [x] Actualizar documentación en Brand Factory.
- [x] Las data card y las media card en la librería de desktop tienen el ancho de los textos en "fixed" pero debería estar en "fill"

**Comment by aweell** [comment]
Evaluar los cambios a realizar:

* Data vs SnapCard
* DataCard + circle + snapcard change variant prop
* Deprecar DataCard -> Nueva DataCard con circle
* Crear superCard y deprecar existentes

**Comment by AnaMontes11** [comment]
Dadas las diferentes alternativas que ha expuesto Álex, y que cada una de ellas conlleva algún tipo de breaking change, proponemos debatir los puntos anteriores en una reunión conjunta.
Por el momento la review la dejo como **Paused**

**Comment by AnaMontes11** [comment]
Tras la reunión decidimos:
- SnapCard --> change original variant prop
- DataCard --> mantenemos lo que hay actualmente

Posible evolución a largo plazo: 
- Habilitar posible "slot" para incluir logos en la parte superior de la DataCard
- Valorar si tiene sentido crear una SuperCard
