### ISSUE TITLE
Popover / trigger alignment

### ISSUE THREAD

**Issue by aweell** [Telefonica/mistica-design#786]
The current popover definition only allows to define the dialog position between top, right, bottom and left positions (web) and top and bottom positions (native).

![Screenshot 2022-09-20 at 14 54 12](https://user-images.githubusercontent.com/44420072/191263061-1e36fdf8-da85-43df-8937-d291874f1d22.png)

When displayed in web it's not possible to define how the dialog is aligned with the trigger, resulting in the dialog being aligned:

* For top and bottom positions: starting from the left
* For left and right positions: centered to the trigger

The idea is to be possible to align the popover dialog to the start, center and end of the trigger area. 

![Screenshot 2022-09-20 at 14 57 32](https://user-images.githubusercontent.com/44420072/191263806-94b35873-5c51-497a-8265-ff882df1172b.png)

## Tasks

- [ ] Add to the spec the aligment properties
- [ ] Update popover in desktop library
- [ ] Update popover in mobile library

## Notes

I see two different ways to approach this:

* Add more positions: instead of position top, position top-right, top-center, top-left (Reference: https://ant.design/components/popover/)
* Add a new prop alignment: position: top, align: center, right, left
