### ISSUE TITLE
Header evolution

### ISSUE THREAD

**Issue by yceballost** [Telefonica/mistica-design#901]
# This evolution include 
- [x] Bleed headers
- [x] Removed Pre title + Digit + Buttons + Subtitle
	- Now this kind of compositions have to be built in slot area
- [x] Added Description

## Tasks
- [x] Update specs
- [x] https://github.com/Telefonica/mistica-design/issues/926
- [x] Design documentation
- [x] Add to mobile library
- [x] Add to desktop library
- [x] Add to UI Kit
- [x] [Web ticket ](https://jira.tid.es/browse/WEB-758)
- [x] [iOS Ticket](https://jira.tid.es/browse/IOS-8008)
- [x] [Android Ticket](https://jira.tid.es/browse/ANDROID-11574)

### Discussed in https://github.com/Telefonica/mistica-design/discussions/493

<div type='discussions-op-text'>

<sup>Originally posted by **yceballost** June 24, 2022</sup>
![image](https://user-images.githubusercontent.com/6722153/175555646-eae4e316-b931-4df1-8f48-40d32eba8bce.png)

Actualmente un header tiene los elementos de la parte superior, creo que esto componente nació con demasiados elementos pensados para casos muy concretos, como lo son ese Pretitle + amount + buttons

Creo que este componente debería evolucionar a tener un pretitle, title y subtitle, y el resto debería ser un slot.

![image](https://user-images.githubusercontent.com/6722153/175555985-c9238f44-ae36-4902-9b7d-77695136a292.png)
</div>

**Comment by yceballost** [comment]
Merging https://github.com/Telefonica/mistica-design/issues/888 here
